[workspace.package]
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
license = "Apache-2.0"
repository = "https://github.com/iotaledger/notarization.rs"
rust-version = "1.65"

[workspace]
resolver = "2"
members = [
    "notarization",
    "experimental_notarization",
]

[workspace.dependencies]
anyhow = "1.0.95"
cfg-if = "1.0.0"
identity_iota_interaction = { git = "https://github.com/iotaledger/identity.rs.git", branch = "feat/identity-rebased-alpha", package = "identity_iota_interaction" }
secret-storage = { git = "https://github.com/iotaledger/secret-storage.git", tag = "v0.1.0", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false }
strum = { version = "0.25", default-features = false, features = ["std", "derive"] }
thiserror = { version = "1.0", default-features = false }





[workspace.lints.clippy]
result_large_err = "allow"