# Copyright (c) 2024 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

[package]
name = "IotaNotarization"
edition = "2024.beta"

[dependencies]
# 'tag' keyword not supported here, therefore use rev instead
# 'tag = "v0.10.3-rc"' equals 'rev = "21768a84e4fe2815ea7f674db645269ae8546d07"', which we use here
MoveStdlib = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/move-stdlib", rev = "21768a84e4fe2815ea7f674db645269ae8546d07" }
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "21768a84e4fe2815ea7f674db645269ae8546d07" }

[addresses]
iota_notarization = "0x0"

[dev-dependencies]

[dev-addresses]
