name: 'iota-cli setup'
description: 'Setup IOTA CLI for Linux or MacOS'

inputs:
  platform:
    description: 'Platform to download binary for (linux or macos)'
    required: true
    default: 'linux'
  logfile:
    description: 'Optional log file to store server log as workflow artifact'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up IOTA CLI
      shell: bash
      run: |
        set -e
        mkdir -p iota
        cd iota

        # Set platform
        PLATFORM="${{ inputs.platform }}"
        echo "Looking for platform: $PLATFORM"

        # pinned releases from:
        # url = https://api.github.com/repos/iotaledger/iota/releases/latest
        # releases might be visible before all binaries are available, so refer to fixed binaries here
        if [ "$PLATFORM" = "linux" ]; then
          DOWNLOAD_URL="https://github.com/iotaledger/iota/releases/download/v0.11.6-rc/iota-v0.11.6-rc-linux-x86_64.tgz"
        elif [ "$PLATFORM" = "macos" ]; then
          DOWNLOAD_URL="https://github.com/iotaledger/iota/releases/download/v0.11.6-rc/iota-v0.11.6-rc-macos-arm64.tgz"
          brew install postgresql
          brew reinstall libpq
        else
          echo "No binaries available for platform: $PLATFORM"
          exit 1
        fi

        # Download and extract
        echo "Downloading from: $DOWNLOAD_URL"
        curl -L -o iota.tar.gz $DOWNLOAD_URL
        tar -xzf iota.tar.gz

        echo "$PWD" >> $GITHUB_PATH
        export PATH="$PWD:$PATH"

        which iota || echo "iota not found in PATH"
        ls -la "$PWD"

        # Verify installation
        iota --version
        echo "IOTA CLI setup completed successfully."

