[package]
name = "notarization"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "tangle", "utxo", "notarization"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "A data notarization toolkit for the IOTA Ledger."

[dependencies]
anyhow.workspace = true
cfg-if.workspace = true
fastcrypto.workspace = true
phf.workspace = true
product_common.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
strum.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iota_interaction.workspace = true
iota_interaction_rust.workspace = true
iota-config = { git = "https://github.com/iotaledger/iota.git", package = "iota-config", tag = "v0.11.6-rc" }
iota-sdk = { git = "https://github.com/iotaledger/iota.git", package = "iota-sdk", tag = "v0.11.6-rc" }
move-core-types = { git = "https://github.com/iotaledger/iota.git", package = "move-core-types", tag = "v0.11.6-rc" }
secret-storage = { git = "https://github.com/iotaledger/secret-storage.git", tag = "v0.3.0" }
shared-crypto = { git = "https://github.com/iotaledger/iota.git", package = "shared-crypto", tag = "v0.11.6-rc" }
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync", "rt", "process"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
iota_interaction = { git = "ssh://git@github.com/iotaledger/product-core.git", branch = "feat/extensions-needed-for-notarization", package = "iota_interaction", default-features = false }
#iota_interaction = { path = "../../product-core/iota_interaction", default-features = false }
iota_interaction_ts = { git = "ssh://git@github.com/iotaledger/product-core.git", branch = "feat/extensions-needed-for-notarization", package = "iota_interaction_ts" }
#iota_interaction_ts = { path = "../../product-core/bindings/wasm/iota_interaction_ts" }
secret-storage = { git = "https://github.com/iotaledger/secret-storage.git", default-features = false, tag = "v0.3.0" }

[dev-dependencies]
async-trait.workspace = true
identity_jose = { git = "https://github.com/iotaledger/identity.rs.git", branch = "feat/identity-rebased-alpha-public-interaction-rust", package = "identity_jose" }
identity_storage = { git = "https://github.com/iotaledger/identity.rs.git", branch = "feat/identity-rebased-alpha-public-interaction-rust", package = "identity_storage", features = ["send-sync-storage", "storage-signer"] }
iota_interaction = { git = "ssh://git@github.com/iotaledger/product-core.git", branch = "feat/extensions-needed-for-notarization", package = "iota_interaction", features = ["keytool-signer"] }
#iota_interaction = { path = "../../product-core/iota_interaction", features = ["keytool-signer"] }
lazy_static = "1.5.0"

