# Copyright (c) 2024 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

[package]
name = "IotaNotarization"
edition = "2024.beta"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "e694e2ee8f2f9f0b9b03b843a24ff0f7bcff2930" }

[addresses]
iota_notarization = "0x0"

[dev-dependencies]

[dev-addresses]
